import type { Metadata } from 'next'
import { StackProvider } from "@stackframe/stack";

import { stackServerApp } from "../stack";
import ConvexClientProvider from '../components/ConvexClientProvider';
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}><StackProvider app={stackServerApp}><ConvexClientProvider>{children}</ConvexClientProvider></StackProvider></body>
    </html>
  )
}
